ALTER TABLE IF EXISTS public.creators
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS social_platforms JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS packages JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS turnaround_days INTEGER DEFAULT 5,
  ADD COLUMN IF NOT EXISTS portfolio_urls JSONB DEFAULT '[]';
